### PR TITLE
feature: add actix server to docker-compose

### PR DESCRIPTION
**Pull request by drew-harris**

### CODE REVIEW

**Comment by drew-harris** [comment]
Still need to get the keycloak environment variables working with the redirect url

**Comment by drew-harris** [comment]
Server complains when the keycloak server is http://actix-web-server-keycloak:8080 but the issuer in the credentials is localhost:8080

https://stackoverflow.com/questions/70697745/keycloak-token-verification-fails-when-the-backend-is-running-in-a-docker-contai
https://www.keycloak.org/server/hostname

These are my current leads. Gonna switch to combining the postgres databases now.

**Comment by drew-harris** [comment]
fixes #12

**Comment by cdxker** [comment]
Not able to solve this issue either. We are going to need to seek some outside help for this issue to be closed.

**Pull request closed without merging**
